accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [

    url(r'^signup/$', views.SignupView, name="signup"),
    url(r'^login/$', views.LoginView, name="login"),
    url(r'^logout/$', views.LogoutView, name="logout"),


]

playlist/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
app_name = 'playlist'
urlpatterns = [
    url(r'^$', views.playlist_list, name="list"),
]

webapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin', admin.site.urls),
    url(r'^playlist/', include('playlist.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^about/$', views.about, name="about"),
    url(r'^$', views.homepage, name="home"),
]


if settings.DEBUG:
    urlpatterns= urlpatterns + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    urlpatterns= urlpatterns + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)



if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns= urlpatterns + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

playlist/models.py
from django.db import models
from django.contrib.auth.models import User
import math
from time import strftime, gmtime
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
import datetime
from .models import User


class Product(models.Model):
    title = models.CharField(max_length=200, verbose_name="product name")
    description = models.TextField()
    thumbnail = models.ImageField(upload_to="thumbnails", blank=False)
    created_at = models.DateTimeField(verbose_name='Created At', default=timezone.now)


















    # artist = models.ForeignKey(Artist, related_name='songs', on_delete=models.CASCADE, default=None)
# class Playlist(models.Model):
# audio_id = models.TextField()
#     title = models.CharField(max_length=200, help_text="Enter a name for your playlist")
#     slug = models.SlugField()
#     date = models.DateTimeField(auto_now_add=True)
#     thumbnail = models.ImageField(default='default.png', blank=True)
#     creater = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
#     def __str__(self):
#         return self.title
#
#
# # class Tracks(models.Model):
# #     title = models.CharField(max_length=200)
# #     date = models.DateTimeField(auto_now_add=True)
# #
# #     def __str__(self):
# #         return self.title
#
# class Genre(models.Model):
#     name = models.CharField(max_length=100, help_text='Enter a music genre (e.g. Psychedelic Rock)')
#
#     def __str__(self):
#         return self.name
#
#
# class Artist(models.Model):
#     name = models.CharField(max_length=255)
#     slug = models.SlugField()
#     description = models.TextField(default=None)
#     genre = models.ManyToManyField(Genre)
#     date_of_birth = models.DateField(null=True, blank=True)
#     date_of_death = models.DateField('Died', null=True, blank=True)
#
#     def display_genre(self):
#         return ', '.join(genre.name for genre in self.genre.all()[:3])
#
#     display_genre.short_description = 'Genre'
#
#     def __str__(self):
#         return self.name
#
#
#     def save(self, *args, **kwargs):
#         self.slug = slugify(self.name)
#         super(Artist, self).save(*args, **kwargs)
#
#
# class Album(models.Model):
#     name = models.CharField(max_length=50)
#     artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
#     genre = models.ManyToManyField(Genre)
#
#     def display_genre(self):
#         return ', '.join(genre.name for genre in self.genre.all()[:3])
#
#     display_genre.short_description = 'Genre'
#
#     def __str__(self):
#         return self.name
#

    # genre = models.ManyToManyField(Genre)

    # def display_genre(self):
    #     return ', '.join(genre.name for genre in self.genre.all()[:3])
    #
    # display_genre.short_description = 'Genre'

    # @property
    # def duration(self):
    #     return str(strftime('%H:%M:%S', gmtime(float(self.playtime))))
    #
    # @property
    # def file_size(self):
    #     if self.size == 0:
    #         return "0B"
    #     size_name = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
    #     i = int(math.floor(math.log(self.size, 1024)))
    #     p = math.pow(1024, i)
    #     s = round(self.size / p, 2)
    #     return "%s %s" % (s, size_name[i])
    #
    #     def __str__(self):
    #         return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms.widgets import PasswordInput, TextInput

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required', label='', label_suffix='', widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'E-Mail'}
        ))
    username = forms.CharField(max_length=200, label='', label_suffix='', widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Username'}
        ))
    password1 = forms.CharField(max_length=200, label='', label_suffix='',widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Password'}
        ))
    password2 = forms.CharField(max_length=200, label='', label_suffix='', widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Retype Password'}
        ))
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

        def save(self, commit=True):
            user = super(SignupForm, self).save(commit=False)
            user.email = cleaned_data['email']

            if commit:
                user.save()

                return user

class LoginForm(AuthenticationForm):
     username = forms.CharField(widget=TextInput(attrs={'class':'validate','placeholder': 'Email'}))
     password = forms.CharField(widget=PasswordInput(attrs={'placeholder':'Password'}))

accounts/views.py
from .forms import SignupForm, LoginForm
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout


def SignupView(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            return redirect('accouonts/login.html')
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {'form': form})


def LoginView(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/templates/homepage.html')

    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', { 'form': form })


def LogoutView(request):
    if request.method == 'POST':
            logout(request)
            return redirect('templates/homepage.html')

playlist/views.py
from django.shortcuts import render
from playlist.models import Product
from django.views import generic

def playlist_list(request):
    products = Product.objects.all().order_by('created_at');
    context = {
    'products': products,
    }
    return render(request, 'playlist/playlist_list.html', context=context)


# class Playlist_List(generic.ListView):
#     model = Playlist

webapp/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html')

def about(request):
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<h2 class="login-h2">Login to start <span><i><strong>Creating</strong></i></span></h2>
<img class="login-img" src="/assets/picture4.jpg" alt="">
<div class="login">
  <form class="loginform" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input class="loginbutton" type="submit" value="Login">
  </form>
  <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<h2 class="signup-h2">Register to begin your <span><i><strong>journey</strong></i></span></h2>
<img class="signup-img" src="/assets/picture2.jpg" alt="">
 <div class="signup">
    <form class="signupform" method="post">
      {% csrf_token %}
      {% for field in form %}
        <p>
          {{ field.label_tag }}<br>
          {{ field }}
          {% for error in field.errors %}
          </p>
          <p class="errortext">{{ error }}</p>
          {% endfor %}
      {% endfor %}
       <button class="signupbutton"type="submit">Register Me</button>
    </form>
   </div>
{% endblock %}

playlist/templates/playlist/playlist_list.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content%}
    <div class="playlists">
      <div class="playlist">
        <ul>
          {% for product in products %}
          <li>
            <img src="{{ playlist.thumbnail.url }}" alt="">
            <h2><a href="{{ playlist.get_absolute_url }}">{{ product.title }}</a></h2>
            <p>{{ product.created_at }}</p>
            <p>{{ product.description }}</p>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
{% endblock %}

templates/about.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin">
    </head>
    <body class="about">
      <div>
        <h1>About</h1>
        <p>Hi. I am a guy from a less known city of a dystopian country, while I'm not lost and consumed by the sheer pressure of human survival,
        I smoke and create stuff, in the hope of finding the long lost peace that we all crave along the way. </p>
      </div>
    </body>
</html>

templates/base_layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>A Ride</title>
        {% load static %}
        <script type="text/javascript" src="assets/js/sandbox.js">

        </script>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=Sura:wght@700&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Staatliches&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Engagement&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Esteban&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Fira+Sans+Condensed:wght@600&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Yellowtail&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@1,500&display=swap">
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin">
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css2?family=Alata&display=swap">
        <nav class="navbar">
          <div class="topnav d-flex flex-row-reverse">
              <ul>
                <li class="nav-item"><a class="about-link navbar-link" href="/about/">About</a></li>
                <li class="nav-item"><a class="products-link nav-link" href="{% url 'playlist:list' %}">Products</a></li>
                <li class="nav-item"><a class="signup-link nav-link" href="{% url 'accounts:signup' %}">Signup</a></li>
                <li class="nav-item"><a id="login-link nav-link" href="{% url 'accounts:login' %}">Login</a></li>
              </ul>
          </div>
        </nav>

    </head>
  <body>
    <div class="wrapper">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

templates/homepage.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content%}

<body>
  <header class="header">
    <div class="background">
      <img class="background-picture" src="assets/picture5.jpg" alt="">
    </div>

    </header>
    <div class="homepage">
      <div class="left-side">
        <div class="cat-picture">
          <img src="assets/picture6.jpg" alt="">
        </div>
        <div class="texts">
          <h1 class="sena">Senallica<span class="leather">Leather Gallery</span></h1>
        </div>
      </div>
      <div class="right-side">
        <h1>We make handmaid leather for your unique taste</h1><br>
        <a href="/nothing/now">Shop Now</a>
      </div>
    </div>
  <main>
    <section class="shop-section">
        <div class="card-grid">
          <!-- <div class="svg-text"> -->
            <!-- <h4>Take a peak at our catalog</h4>
            <div class="svg">
              <img src="assets/shoppingsvg.svg" alt="svg" height="200px" width="100px">
            </div> -->
              <a class="card" id="card1" href="#">
                <div class="card-div">
                  <div class="card-background">
                    <img src="assets/lighter.jpg" alt="">
                  </div>
                  <div class="card-content">
                    <p class="card-category">Lighters</p>
                    <h3 class="card-heading">Custom made Lighters</h3>
                  </div>
                </div>
              </a>
              <a class="card" id="card2" href="#">
                <div class="card-div">
                  <div class="card-background">
                    <img src="assets/leather.jpg" alt="">
                  </div>
                  <div class="card-content">
                    <p class="card-category">Leather</p>
                    <h3 class="card-heading">High quality leathers clothing</h3>
                  </div>
                </div>
              </a>
              <a class="card" id="card3" href="{% url 'playlist:list' %}">
                <div class="card-div">
                  <div class="card-background">
                    <img src="assets/stickers.jpg" alt="">
                  </div>
                  <div class="card-content">
                    <p class="card-category">Stickers</p>
                    <h3 class="card-heading">Creativly designed stickrs</h3>
                  </div>
                </div>
              </a>
            </div>
          </section>
          <div class="freeshipping-text">
            <h1><span class="freeshipping-span">Everything</span>
              <span class="freeshipping-span">comes with</span>
              <span class="freeshipping-span">Free shipping</span>
            </h1>
          </div>
        </main>

      </body>
        {% endblock %}